import { Locale } from "@/lib/i18n";
import { CategorySlug, SortKey } from "@/lib/catalog";

export const siteContent = {
  uk: {
    home: {
      heroKicker: "Весна / Літо 2026",
      heroTitle: "Маки",
      heroCta: "Відкрити колекцію",
      categoryImages: {
        dresses: "https://www.nadiyadumka.com/cdn/shop/files/d_lb_i-132.jpg?v=1776528884",
        suits: "https://www.nadiyadumka.com/cdn/shop/files/IMG_3283.jpg?v=1776515319",
        evening: "https://www.nadiyadumka.com/cdn/shop/files/IMG_3246.jpg?v=1776677568",
      },
      promoKicker: "Фільм колекції",
      promoTitle: "МАКИ у русі",
      promoText:
        "Тканина, силует і жест збираються в одну живу історію нової колекції.",
      promoCta: "Дивитися історію",
      statementKicker: "DUMKA by Nadiya Dumka",
      statement:
        "Нова колекція «Маки» збирає м'якість пелюстки й силу лінії в образи для літа, вечора та подій, де важлива присутність.",
      collectionKicker: "Добірка сезону",
      collectionTitle: "Весна - літо 2026",
      fittingCta: "Записатися на примірку",
      categoryTitles: {
        dresses: "Сукні",
        suits: "Костюми",
        evening: "Вечірній одяг",
      },
      categoryCta: "До каталогу",
      lookbookKicker: "Нова колекція / Весна-літо 2026",
      lookbookTitle:
        "Макова тема переходить у чисті силуети, напругу червоного акценту та спокійну архітектуру вечірнього одягу.",
      lookbookCta: "Дивитися образи",
      mediaKicker: "Медіа",
      mediaTitle: "Прес-центр",
      media: [
        "Головні тренди сезону осінь-зима 2025/26 з подіумів Ukrainian Fashion Week",
        "Колекція GRONO від DUMKA by Nadiya Dumka",
        "FW25-26: DUMKA показ",
      ],
      showroomKicker: "Офлайн бутик",
      showroomTitle: "Примірка у флагманському просторі DUMKA у Львові.",
      showroomCta: "Запланувати візит",
      address: ["Вул. Шпитальна, 1", "Львів", "ТЦ \"Магнус\", 3-й поверх", "+38 (067) 757-01-21"],
    },
    catalog: {
      eyebrow: "Магазин / DUMKA",
      title: "Каталог",
      intro: "Речі для подій, примірок і моментів, де силует говорить тихіше за логотип.",
      itemWord: "виробів",
      showroom: "Львівський шоурум",
      season: "Весна - літо 2026",
      categories: "Категорії",
      sorting: "Сортування",
      filters: "Фільтри",
      filtersTitle: "Фільтри каталогу",
      clear: "Очистити",
      showAll: "Показати всі",
      show: "Показати",
      emptyTitle: "Нічого не знайдено",
      emptyText:
        "У цій категорії поки немає виробів. Перегляньте повний каталог або заплануйте примірку в шоурумі.",
      errorTitle: "Каталог тимчасово недоступний",
      contactShowroom: "Зв'язатися з шоурумом",
      categoryLabels: {
        all:         "Усі",
        suits:       "Костюми",
        dresses:     "Сукні",
        evening:     "Вечірній одяг",
        jackets:     "Жакети",
        vests:       "Жилети",
        blouses:     "Блузи",
        skirts:      "Спідниці",
        trousers:    "Штани",
        tops:        "Топи",
        shorts:      "Шорти",
        jumpsuits:   "Комбінезони",
        leather:     "Шкіряні вироби",
        corsets:     "Корсети",
        accessories: "Аксесуари",
        sets:        "Комплекти",
        gifts:       "Подарунки",
        other:       "Інше",
      } satisfies Record<CategorySlug, string>,
      sortLabels: {
        featured:    "Рекомендоване",
        "price-asc": "Ціна: від нижчої",
        "price-desc":"Ціна: від вищої",
        "name-asc":  "Назва: А-Я",
      } satisfies Record<SortKey, string>,
    },
    product: {
      kicker: "DUMKA для особливих подій",
      size: "Розмір",
      sizeGuide: "Розмірна сітка",
      someUnavailable: "Окремі варіанти цього розміру недоступні",
      available: "В наявності",
      unavailable: "Немає в наявності",
      addToCart: "Додати до кошика",
      description: "Опис",
      descriptionFallback:
        "Виріб створено з увагою до посадки, силуету та відчуття тканини на тілі.",
      care: "Тканина та догляд",
      careText: "Тільки професійна суха чистка. Не прати. Не відбілювати.",
      delivery: "Доставка та повернення",
      deliveryText:
        "Безкоштовна доставка Новою Поштою по Україні протягом 1-3 днів. Повернення можливе протягом 14 днів з моменту отримання.",
      styling: "Стилізація",
      related: "Доповніть образ",
      sizeGuideText:
        "Оберіть розмір за мірками тіла. Якщо виріб має складний крій або ви між двома розмірами, шоурум допоможе підібрати посадку перед замовленням.",
      sizeTable: {
        size: "Розмір",
        bust: "Груди",
        waist: "Талія",
        hips: "Стегна",
      },
      sizeNotes: ["Мірки вказано в сантиметрах", "Крій може змінювати посадку", "Примірка: Львів, ТЦ “Магнус”"],
      close: "Закрити",
    },
    footer: {
      text:
        "Речі для подій, що залишаються у пам'яті. Шоурум у ТЦ \"Магнус\", індивідуальна примірка та уважний сервіс.",
      emailLabel: "Електронна пошта для листа з колекцією",
      links: ["Колекція", "Шоурум", "Лукбук", "Історії"],
      serviceLinks: ["Доставка", "Повернення", "Instagram", "Facebook", "TikTok"],
      address: ["вул. Шпитальна, 1, Львів", "“Магнус”, 3-й поверх", "dumkaprotebe@gmail.com", "+38 (067) 757-01-21"],
    },
  },
  en: {
    home: {
      heroKicker: "Spring / Summer 2026",
      heroTitle: "Maky",
      heroCta: "Open collection",
      categoryImages: {
        dresses: "https://www.nadiyadumka.com/cdn/shop/files/d_lb_i-132.jpg?v=1776528884",
        suits: "https://www.nadiyadumka.com/cdn/shop/files/IMG_3283.jpg?v=1776515319",
        evening: "https://www.nadiyadumka.com/cdn/shop/files/IMG_3246.jpg?v=1776677568",
      },
      promoKicker: "Collection film",
      promoTitle: "MAKY in motion",
      promoText:
        "Fabric, silhouette, and gesture come together in one living story of the new collection.",
      promoCta: "Watch the story",
      statementKicker: "DUMKA by Nadiya Dumka",
      statement:
        "The Maky collection gathers petal softness and a precise line into pieces for summer, evening, and moments that call for presence.",
      collectionKicker: "Curated edit",
      collectionTitle: "Spring - Summer 2026",
      fittingCta: "Book a fitting",
      categoryTitles: {
        dresses: "Dresses",
        suits: "Suits",
        evening: "Evening wear",
      },
      categoryCta: "Shop now",
      lookbookKicker: "New collection / Spring-Summer 2026",
      lookbookTitle:
        "The poppy motif moves into clean silhouettes, a quiet red accent, and the calm architecture of eveningwear.",
      lookbookCta: "View looks",
      mediaKicker: "Media",
      mediaTitle: "Press center",
      media: [
        "Key autumn-winter 2025/26 trends from Ukrainian Fashion Week",
        "The GRONO collection by DUMKA by Nadiya Dumka",
        "FW25-26: DUMKA presentation",
      ],
      showroomKicker: "Offline boutique",
      showroomTitle: "A fitting at the DUMKA flagship space in Lviv.",
      showroomCta: "Plan a visit",
      address: ["Shpytalna St, 1", "Lviv", "Magnus shopping center, 3rd floor", "+38 (067) 757-01-21"],
    },
    catalog: {
      eyebrow: "Shop / DUMKA",
      title: "Catalog",
      intro: "Pieces for events, fittings, and moments where silhouette speaks quieter than a logo.",
      itemWord: "pieces",
      showroom: "Lviv showroom",
      season: "Spring - Summer 2026",
      categories: "Categories",
      sorting: "Sorting",
      filters: "Filters",
      filtersTitle: "Catalog filters",
      clear: "Clear",
      showAll: "Show all",
      show: "Show",
      emptyTitle: "No pieces found",
      emptyText:
        "There are no pieces in this category yet. View the full catalog or book a showroom fitting.",
      errorTitle: "Catalog temporarily unavailable",
      contactShowroom: "Contact showroom",
      categoryLabels: {
        all:         "All",
        suits:       "Suits",
        dresses:     "Dresses",
        evening:     "Evening wear",
        jackets:     "Jackets",
        vests:       "Vests",
        blouses:     "Blouses",
        skirts:      "Skirts",
        trousers:    "Trousers",
        tops:        "Tops",
        shorts:      "Shorts",
        jumpsuits:   "Jumpsuits",
        leather:     "Leather outfits",
        corsets:     "Corsets",
        accessories: "Accessories",
        sets:        "Sets",
        gifts:       "Gifts",
        other:       "Other",
      } satisfies Record<CategorySlug, string>,
      sortLabels: {
        featured:    "Featured",
        "price-asc": "Price: low to high",
        "price-desc":"Price: high to low",
        "name-asc":  "Name: A-Z",
      } satisfies Record<SortKey, string>,
    },
    product: {
      kicker: "DUMKA made-to-occasion",
      size: "Size",
      sizeGuide: "Size guide",
      someUnavailable: "Some variants in this size are unavailable",
      available: "Available",
      unavailable: "Unavailable",
      addToCart: "Add to cart",
      description: "Description",
      descriptionFallback:
        "Created with attention to fit, silhouette, and the feel of fabric on the body.",
      care: "Fabric and care",
      careText: "Professional dry clean only. Do not wash. Do not bleach.",
      delivery: "Delivery and returns",
      deliveryText:
        "Complimentary Nova Poshta delivery in Ukraine within 1-3 days. Returns are available within 14 days of receipt.",
      styling: "Styling",
      related: "Complete the look",
      sizeGuideText:
        "Choose your size by body measurements. If the cut is complex or you are between sizes, the showroom can help refine the fit before ordering.",
      sizeTable: {
        size: "Size",
        bust: "Bust",
        waist: "Waist",
        hips: "Hips",
      },
      sizeNotes: ["Measurements are in centimeters", "Cut may affect the fit", "Fitting: Lviv, Magnus"],
      close: "Close",
    },
    footer: {
      text:
        "Pieces for events that stay in memory. A showroom at Magnus, individual fittings, and attentive service.",
      emailLabel: "Email for the collection letter",
      links: ["Collection", "Showroom", "Lookbook", "Stories"],
      serviceLinks: ["Delivery", "Returns", "Instagram", "Facebook", "TikTok"],
      address: ["Shpytalna St, 1, Lviv", "Magnus, 3rd floor", "dumkaprotebe@gmail.com", "+38 (067) 757-01-21"],
    },
  },
} as const;

export function getSiteContent(locale: Locale) {
  return siteContent[locale];
}
